core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('kullanici/', include('user.urls')),
    path('stok/', include('inventory.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('urun/<int:pk>/', views.product_detail, name='product_detail'),
    path('urun/ekle/', views.product_create, name='product_create'),
    path('urun/<int:pk>/duzenle/', views.product_update, name='product_update'),
    path('urun/<int:pk>/sil/', views.product_delete, name='product_delete'),
    path('kategoriler/', views.category_list, name='category_list'),
    path('kategori/ekle/', views.category_create, name='category_create'),
    path('raporlar/', views.reports, name='reports'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('giris/', views.login_view, name='login'),
    path('cikis/', views.logout_view, name='logout'),
    path('kayit/', views.register_view, name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>STOKMAN - {% block pagetitle %}{% endblock %}</title>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/logo1.png' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl-carousel/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl-carousel/css/owl.theme.default.min.css' %}">
    <link href="{% static 'vendor/jqvmap/css/jqvmap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">



</head>

<body>

    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>

    <div id="main-wrapper">

        <div class="nav-header">
            <a href="{% url 'index' %}" class="brand-logo" style="display: flex; align-items: center; justify-content: center; width: 100%; padding: 20px 0 !important;">
                <img class="brand-title" src="{% static 'images/logo1.png' %}" alt="STOKMAN" style="max-width: 140px; height: auto; object-fit: contain;">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>

        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                            <div class="search_bar dropdown">
                                <span class="search_icon p-3 c-pointer" data-toggle="dropdown">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <div class="dropdown-menu p-0 m-0">
                                    <form>
                                        <input class="form-control" type="search" placeholder="Arama" aria-label="Search">
                                    </form>
                                </div>
                            </div>
                        </div>

                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <i class="mdi mdi-account"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{% url 'admin:index' %}" class="dropdown-item">
                                        <i class="icon-settings"></i>
                                        <span class="ml-2">Admin Panel</span>
                                    </a>
                                    <a href="{% url 'user:logout' %}" class="dropdown-item">
                                        <i class="icon-key"></i>
                                        <span class="ml-2">Çıkış Yap</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        <div class="quixnav">
            <div class="quixnav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label first">Ana Menü</li>
                    <li><a class="" href="{% url 'index' %}" aria-expanded="false"><i
                        class="icon icon-layout-25"></i><span class="nav-text">Gösterge Paneli</span></a>
                    </li>
                    
                    <li class="nav-label">Stok Yönetimi</li>
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i
                                class="icon icon-bag"></i><span class="nav-text">Ürünler</span></a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'inventory:product_list' %}">Tüm Ürünler</a></li>
                            <li><a href="{% url 'inventory:product_create' %}">Yeni Ürün Ekle</a></li>
                            <li><a href="{% url 'inventory:category_list' %}">Kategoriler</a></li>
                        </ul>
                    </li>
                    
                    <li class="nav-label">Raporlar</li>
                    <li><a href="{% url 'inventory:reports' %}" aria-expanded="false"><i
                                class="icon icon-chart"></i><span class="nav-text">İstatistikler</span></a>
                    </li>
                    
                    <li class="nav-label">Ayarlar</li>
                    <li><a href="{% url 'admin:index' %}" aria-expanded="false"><i class="icon icon-settings"></i><span
                                class="nav-text">Admin Panel</span></a></li>
                </ul>
            </div>
        </div>

        <div class="content-body">
            <!-- row -->
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>
                
        <div class="footer">
            <div class="copyright">
                <p>Copyright © 2025 - Stok Yönetim Sistemi | <a href="#" target="_blank">Eyüphan İpek</a></p>
            </div>
        </div>

    </div>

    <script src="{% static 'vendor/global/global.min.js' %}"></script>
    <script src="{% static 'js/quixnav-init.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>


    <!-- Vectormap -->
    <script src="{% static 'vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'vendor/morris/morris.min.js' %}"></script>


    <script src="{% static 'vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'vendor/chart.js/Chart.bundle.min.js' %}"></script>

    <script src="{% static 'vendor/gaugeJS/dist/gauge.min.js' %}"></script>

    <!--  flot-chart js -->
    <script src="{% static 'vendor/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'vendor/flot/jquery.flot.resize.js' %}"></script>

    <!-- Owl Carousel -->
    <script src="{% static 'vendor/owl-carousel/js/owl.carousel.min.js' %}"></script>

    <!-- Counter Up -->
    <script src="{% static 'vendor/jqvmap/js/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'vendor/jqvmap/js/jquery.vmap.usa.js' %}"></script>
    <script src="{% static 'vendor/jquery.counterup/jquery.counterup.min.js' %}"></script>


    <script src="{% static 'js/dashboard/dashboard-1.js' %}"></script>

</body>

</html>